import type { CraftAsset } from '#shared/types/base'

export const DummyImage: CraftAsset[] = [
  {
    metadata: {
      id: 1,
      filename: 'placeholder.png',
      kind: 'image',
      size: '12345',
      mimeType: 'image/png',
      extension: 'png',
      cpEditUrl: '',
      volumeId: 1,
    },
    height: 600,
    width: 800,
    focalPoint: { x: 0.5, y: 0.5 },
    url: 'https://picsum.photos/800/600?random=1',
    title: 'Sample Image 1',
    srcSets: {
      auto: 'https://picsum.photos/800/600?random=1',
    },
    caption: 'Sample caption 1',
    alt: 'Placeholder image 1',
  },
  {
    metadata: {
      id: 2,
      filename: 'placeholder.png',
      kind: 'image',
      size: '12345',
      mimeType: 'image/png',
      extension: 'png',
      cpEditUrl: '',
      volumeId: 1,
    },
    height: 600,
    width: 800,
    focalPoint: { x: 0.5, y: 0.5 },
    url: 'https://picsum.photos/800/600?random=2',
    title: 'Sample Image 2',
    srcSets: {
      auto: 'https://picsum.photos/800/600?random=2',
    },
    caption: 'Sample caption 2',
    alt: 'Placeholder image 2',
  },
  {
    metadata: {
      id: 3,
      filename: 'placeholder.png',
      kind: 'image',
      size: '12345',
      mimeType: 'image/png',
      extension: 'png',
      cpEditUrl: '',
      volumeId: 1,
    },
    height: 600,
    width: 800,
    focalPoint: { x: 0.5, y: 0.5 },
    url: 'https://picsum.photos/800/600?random=3',
    title: 'Sample Image 3',
    srcSets: {
      auto: 'https://picsum.photos/800/600?random=3',
    },
    caption: 'Sample caption 3',
    alt: 'Placeholder image 3',
  },
  {
    metadata: {
      id: 4,
      filename: 'placeholder.png',
      kind: 'image',
      size: '12345',
      mimeType: 'image/png',
      extension: 'png',
      cpEditUrl: '',
      volumeId: 1,
    },
    height: 600,
    width: 800,
    focalPoint: { x: 0.5, y: 0.5 },
    url: 'https://picsum.photos/800/600?random=4',
    title: 'Sample Image 4',
    srcSets: {
      auto: 'https://picsum.photos/800/600?random=4',
    },
    caption: 'Sample caption 4',
    alt: 'Placeholder image 4',
  },
  {
    metadata: {
      id: 5,
      filename: 'placeholder.png',
      kind: 'image',
      size: '12345',
      mimeType: 'image/png',
      extension: 'png',
      cpEditUrl: '',
      volumeId: 1,
    },
    height: 600,
    width: 800,
    focalPoint: { x: 0.5, y: 0.5 },
    url: 'https://picsum.photos/800/600?random=5',
    title: 'Sample Image 5',
    srcSets: {
      auto: 'https://picsum.photos/800/600?random=5',
    },
    caption: 'Sample caption 5',
    alt: 'Placeholder image 5',
  },
  {
    metadata: {
      id: 6,
      filename: 'placeholder.png',
      kind: 'image',
      size: '12345',
      mimeType: 'image/png',
      extension: 'png',
      cpEditUrl: '',
      volumeId: 1,
    },
    height: 600,
    width: 800,
    focalPoint: { x: 0.5, y: 0.5 },
    url: 'https://picsum.photos/800/600?random=6',
    title: 'Sample Image 6',
    srcSets: {
      auto: 'https://picsum.photos/800/600?random=6',
    },
    caption: 'Sample caption 6',
    alt: 'Placeholder image 6',
  },
]
