/**
 * 
 *    ___                             _    ____ ___ 
 *   / _ \ _   _  ___ _ __ _   _     / \  |  _ \_ _|
 *  | | | | | | |/ _ \ '__| | | |   / _ \ | |_) | | 
 *  | |_| | |_| |  __/ |  | |_| |  / ___ \|  __/| | 
 *   \__\_\__,_|\___|_|   \__, | /_/   \_\_|  |___|
 *                         |___/                    
 *           
 * This file was generated by the Query API Type Generator.
 * Please do not edit this file manually. Changes made in this file might get lost.
 * To update it, run the 'craft query-api/typescript/generate-types' command.
 */

// --- hardTypes ---
export type CraftDateTime = {
    date: string
    timezone: string
    timezone_type: number
}

export type CraftColor = {
    hex: string
    rgb: string
    hsl: string
}

export type CraftCountry = {
    name: string
    countryCode: string
    threeLetterCode: string
    locale: string
    currencyCode: string
    timezones: string[]
}

export type CraftMoney = {
    amount: string
    currency: string
}

export type CraftLinkTarget = '_blank' | '_self'

export type CraftLink = {
    elementType: string
    url: string
    label: string
    target: CraftLinkTarget
    rel: string
    urlSuffix: string
    class: string
    id: string
    ariaLabel: string
    download: boolean
    downloadFile: string
}

export type CraftJson = object | object[]

export type CraftAssetFocalPoint = {
    x: number
    y: number
}

export type CraftAssetMeta = {
    id: number
    filename: string
    kind: string
    size: string
    mimeType: string
    extension: string
    cpEditUrl: string
    volumeId: number
}

export type CraftAddressMeta = {
    id: number
}

export type CraftUserStatus = 'inactive' | 'active' | 'pending' | 'credentialed' | 'suspended' | 'locked'

export type CraftUserMeta = {
    id: number
    status: CraftUserStatus
    cpEditUrl: string
}

export type CraftEntryRelation = {
    title: string
    slug: string
    url: string
    id: number
}

export type CraftEntryStatus = 'live' | 'pending' | 'expired' | 'disabled'

export type CraftEntryMeta = {
    id: number
    entryType: string
    sectionId: number
    siteId: number
    url: string
    slug: string
    uri: string
    fullUri: string
    status: CraftEntryStatus
    cpEditUrl: string
}

export interface CraftPageBase {
    metadata: CraftEntryMeta
    sectionHandle: string
    title: string
}

export type CraftTagMeta = {
    id: number
}

export type CraftTag = {
    metadata: CraftTagMeta
    title: string
    slug: string
}

// --- addresses ---
export type CraftAddress = {
    metadata: CraftAddressMeta
    title: string
    addressLine1: string
    addressLine2: string
    addressLine3: string
    countryCode: string
    locality: string
    postalCode: string
    commerceSettings: any
    addressPhone: string | null
    fullName: string | null
}

// --- assets ---
export type CraftAssetRatio = {
    auto: string
}

export type CraftVolumeSiteImages = {
    metadata: CraftAssetMeta
    height: number
    width: number
    focalPoint: CraftAssetFocalPoint
    url: string
    title: string
    srcSets: CraftAssetRatio
    caption: string | null
    alt: string | null
}

export type CraftVolumeSiteDownloads = {
    metadata: CraftAssetMeta
    height: number
    width: number
    focalPoint: CraftAssetFocalPoint
    url: string
    title: string
    srcSets: CraftAssetRatio
    caption: string | null
    alt: string | null
}

export type CraftVolumeSiteGraphics = {
    metadata: CraftAssetMeta
    height: number
    width: number
    focalPoint: CraftAssetFocalPoint
    url: string
    title: string
    srcSets: CraftAssetRatio
    caption: string | null
    alt: string | null
}

export type CraftVolumeSiteUsers = {
    metadata: CraftAssetMeta
    height: number
    width: number
    focalPoint: CraftAssetFocalPoint
    url: string
    title: string
    srcSets: CraftAssetRatio
    caption: string | null
    alt: string | null
}

export type CraftVolumeShopImages = {
    metadata: CraftAssetMeta
    height: number
    width: number
    focalPoint: CraftAssetFocalPoint
    url: string
    title: string
    srcSets: CraftAssetRatio
    caption: string | null
    alt: string | null
}

export type CraftVolumeStickers = {
    metadata: CraftAssetMeta
    height: number
    width: number
    focalPoint: CraftAssetFocalPoint
    url: string
    title: string
    srcSets: CraftAssetRatio
    caption: string | null
    alt: string | null
}

export type CraftAsset = CraftVolumeSiteImages | CraftVolumeSiteDownloads | CraftVolumeSiteGraphics | CraftVolumeSiteUsers | CraftVolumeShopImages | CraftVolumeStickers

// --- entryTypes ---
export interface CraftEntryTypeBlockAccordionContent {
    singleLabel: string
    singleRichText: string
}

export interface CraftEntryTypeBlockBackstage {
    images: (CraftEntryTypeImagesBlock)[]
    linkInfo: CraftLinkIt | null
}

export interface CraftEntryTypeBlockButton {
    singleButton: CraftLinkIt
}

export interface CraftEntryTypeBlockButtonGroup {
    singleButtonGroup: (CraftEntryTypeSingleButtonGroupBlock)[] | null
    settingsButtonGroup: CraftEntryTypeSettingsButtonGroupBlock | null
}

export interface CraftEntryTypeBlockCode {
    singleCode: string
    singleCodeLanguage: CraftOptionSingleCodeLanguage | null
}

export interface CraftEntryTypeBlockEmbed {
    singleEmbedCode: string
    settingsEmbed: CraftEntryTypeSettingsEmbedBlock | null
}

export interface CraftEntryTypeBlockFaq {
    title: string | null
    relatedFaqs: (CraftEntryRelation)[]
    singleButton: CraftLinkIt | null
    isLessSpacingAbove: boolean | null
}

export interface CraftEntryTypeBlockHeadline {
    singleHeadline: string
    settingsHeadline: CraftEntryTypeSettingsHeadlineBlock | null
}

export interface CraftEntryTypeBlockHeadlineNewsletter {
    headline: string
    subline: string | null
    spacingBottom: boolean | null
}

export interface CraftEntryTypeBlockImageCover {
    singleImage: CraftAsset
    singleLink: CraftLinkIt | null
    showCaption: boolean | null
    imageRatio: CraftOptionImageRatio
}

export interface CraftEntryTypeBlockImageCoverDeprecated {
    singleImage: CraftAsset | null
    singleText: string | null
    settingsImageCover: CraftEntryTypeSettingsImageCoverBlock | null
}

export interface CraftEntryTypeBlockImageDouble {
    singleImageDouble: (CraftAsset)[] | null
    settingsImageDouble: CraftEntryTypeSettingsImageDoubleBlock | null
}

export interface CraftEntryTypeBlockImageGrid {
    singleImages: (CraftAsset)[]
    settingsImageGrid: CraftEntryTypeSettingsImageGridBlock | null
}

export interface CraftEntryTypeBlockImageGridCalculated {
    singleImages: (CraftAsset)[] | null
}

export interface CraftEntryTypeBlockImageSlider {
    singleImages: (CraftAsset)[]
    settingsImageSlider: CraftEntryTypeSettingsImageSliderBlock | null
}

export interface CraftEntryTypeBlockImages {
    images: (CraftEntryTypeImagesBlock)[]
    spacingBottom: boolean | null
}

export interface CraftEntryTypeBlockIndividualEntryGrid {
    title: string | null
    selectIndividualEntries: (CraftEntryRelation)[]
    singleButton: CraftLinkIt | null
}

export interface CraftEntryTypeBlockJobs {
}

export interface CraftEntryTypeBlockLink {
    linkInfo: CraftLinkIt
}

export interface CraftEntryTypeBlockProjectTeaser {
    groupedProjectGrid: (CraftEntryTypeGroupedSingle | CraftEntryTypeGroupedDoubles | CraftEntryTypeGroupedQuadruplets)[] | null
}

export interface CraftEntryTypeBlockQuote {
    singleQuote: string
    singleSource: string | null
    singleSourceUrl: CraftLinkIt | null
}

export interface CraftEntryTypeBlockRelatedProjects {
    singleHeadline: string | null
    singleRelatedProjects: (CraftEntryRelation)[]
    isLessSpacingAbove: boolean | null
}

export interface CraftEntryTypeBlockRichText {
    singleRichText: string
    isAnimated: boolean | null
}

export interface CraftEntryTypeBlockRichTextMarginals {
    singleRichText: string | null
}

export interface CraftEntryTypeBlockRichTextNewsletter {
    richTextSimple: string
    spacingBottom: boolean | null
}

export interface CraftEntryTypeBlockSalaryBand {
    experienceLevel: CraftOptionExperienceLevel
    salaryRanges: (CraftTableSalaryRanges)[]
}

export interface CraftEntryTypeEntryTeaser {
    entry: CraftEntryRelation
}

export interface CraftEntryTypeEntryAbout {
    title: string
    textHero: CraftContentBlockTextHero | null
    richTextSimple: string | null
    singleRichText: string | null
    faqs: CraftContentBlockFaqs | null
    entrySettings: CraftContentBlockEntrySettings | null
}

export interface CraftEntryTypeEntryArticle {
    title: string
    singleSeoTitle: string | null
    label: string | null
    singleIntroText: string | null
    singleImageEntry: CraftAsset | null
    newsletterImage: CraftAsset | null
    contentBuilder: (CraftEntryTypeBlockButton | CraftEntryTypeBlockCode | CraftEntryTypeBlockEmbed | CraftEntryTypeBlockFaq | CraftEntryTypeBlockHeadline | CraftEntryTypeBlockImageCover | CraftEntryTypeBlockImageGrid | CraftEntryTypeBlockImageSlider | CraftEntryTypeBlockIndividualEntryGrid | CraftEntryTypeBlockJobs | CraftEntryTypeBlockQuote | CraftEntryTypeBlockRelatedProjects | CraftEntryTypeBlockRichText | CraftEntryTypeBlockSalaryBand | CraftEntryTypeBlockImageCoverDeprecated | CraftEntryTypeBlockButtonGroup | CraftEntryTypeBlockRichTextMarginals | CraftEntryTypeBlockProjectTeaser)[] | null
    singleAuthor: (CraftEntryRelation)[]
    categoryArticles: (CraftEntryRelation)[]
    tagsArticles: (CraftEntryRelation)[] | null
    entrySettings: CraftContentBlockEntrySettings | null
}

export interface CraftEntryTypeEntryArticleTag {
    title: string
}

export interface CraftEntryTypeEntryArticleType {
    title: string
}

export interface CraftEntryTypeEntryArticles {
    entrySettings: CraftContentBlockEntrySettings | null
    title: string
}

export interface CraftEntryTypeEntryAwardType {
    title: string
}

export interface CraftEntryTypeEntryCaseStudy {
    title: string
    singleSeoTitle: string | null
    singleIntroText: string | null
    groupedProjectImages: CraftEntryTypeGroupedProjectImagesBlock
    singleImageEntry: CraftAsset | null
    newsletterImage: CraftAsset | null
    groupedProjectInfo: CraftEntryTypeGroupedProjectInfoBlock | null
    contentBuilderWork: (CraftEntryTypeBlockEmbed | CraftEntryTypeBlockHeadline | CraftEntryTypeBlockButton | CraftEntryTypeBlockImageCover | CraftEntryTypeBlockImageDouble | CraftEntryTypeBlockImageGrid | CraftEntryTypeBlockImageSlider | CraftEntryTypeBlockRichText | CraftEntryTypeBlockQuote | CraftEntryTypeBlockImageGridCalculated | CraftEntryTypeBlockImageCoverDeprecated)[] | null
    settingsAppHeader: boolean | null
    singleAuthor: (CraftEntryRelation)[]
    singleLink: CraftLinkIt | null
    categoryClient: (CraftEntryRelation)[] | null
    categoryPartner: (CraftEntryRelation)[] | null
    singleRelatedProjects: (CraftEntryRelation)[] | null
    categoryAwards: (CraftEntryRelation)[] | null
    categoryService: (CraftEntryRelation)[]
    entrySettings: CraftContentBlockEntrySettings | null
    unitIds: string
}

export interface CraftEntryTypeEntryClient {
    title: string
}

export interface CraftEntryTypeEntryEmbed {
    title: string
    singleEmbedCode: string | null
}

export interface CraftEntryTypeEntryGender {
    title: string
}

export interface CraftEntryTypeEntryGlobals {
    locations: (CraftEntryTypeLocations)[] | null
}

export interface CraftEntryTypeEntryGridImage {
    title: string
    singleImage: CraftAsset | null
    singleSourceUrl: CraftLinkIt | null
}

export interface CraftEntryTypeEntryGridImageWithText {
    title: string
    singleImage: CraftAsset | null
    singleSourceUrl: CraftLinkIt | null
    singleRichText: string | null
}

export interface CraftEntryTypeEntryHomepage {
    title: string
    textHero: CraftContentBlockTextHero | null
    contentBuilder: (CraftEntryTypeBlockButton | CraftEntryTypeBlockCode | CraftEntryTypeBlockEmbed | CraftEntryTypeBlockFaq | CraftEntryTypeBlockHeadline | CraftEntryTypeBlockImageCover | CraftEntryTypeBlockImageGrid | CraftEntryTypeBlockImageSlider | CraftEntryTypeBlockIndividualEntryGrid | CraftEntryTypeBlockJobs | CraftEntryTypeBlockQuote | CraftEntryTypeBlockRelatedProjects | CraftEntryTypeBlockRichText | CraftEntryTypeBlockSalaryBand | CraftEntryTypeBlockImageCoverDeprecated | CraftEntryTypeBlockButtonGroup | CraftEntryTypeBlockRichTextMarginals | CraftEntryTypeBlockProjectTeaser)[] | null
    textWithStickers: CraftContentBlockTextWithStickers | null
    entrySettings: CraftContentBlockEntrySettings | null
}

export interface CraftEntryTypeEntryJob {
    title: string
    singleSeoTitle: string | null
    singleJobLocation: CraftOptionSingleJobLocation
    simpleText: string | null
    singleIntroText: string | null
    singleImageEntry: CraftAsset | null
    newsletterImage: CraftAsset | null
    contentBuilder: (CraftEntryTypeBlockButton | CraftEntryTypeBlockCode | CraftEntryTypeBlockEmbed | CraftEntryTypeBlockFaq | CraftEntryTypeBlockHeadline | CraftEntryTypeBlockImageCover | CraftEntryTypeBlockImageGrid | CraftEntryTypeBlockImageSlider | CraftEntryTypeBlockIndividualEntryGrid | CraftEntryTypeBlockJobs | CraftEntryTypeBlockQuote | CraftEntryTypeBlockRelatedProjects | CraftEntryTypeBlockRichText | CraftEntryTypeBlockSalaryBand | CraftEntryTypeBlockImageCoverDeprecated | CraftEntryTypeBlockButtonGroup | CraftEntryTypeBlockRichTextMarginals | CraftEntryTypeBlockProjectTeaser)[] | null
    faqs: CraftContentBlockFaqs | null
    entrySettings: CraftContentBlockEntrySettings | null
}

export interface CraftEntryTypeEntryJobs {
    title: string
    textHero: CraftContentBlockTextHero | null
    imageCover: CraftEntryTypeBlockImageCover | null
    contentBuilder: (CraftEntryTypeBlockButton | CraftEntryTypeBlockCode | CraftEntryTypeBlockEmbed | CraftEntryTypeBlockFaq | CraftEntryTypeBlockHeadline | CraftEntryTypeBlockImageCover | CraftEntryTypeBlockImageGrid | CraftEntryTypeBlockImageSlider | CraftEntryTypeBlockIndividualEntryGrid | CraftEntryTypeBlockJobs | CraftEntryTypeBlockQuote | CraftEntryTypeBlockRelatedProjects | CraftEntryTypeBlockRichText | CraftEntryTypeBlockSalaryBand | CraftEntryTypeBlockImageCoverDeprecated | CraftEntryTypeBlockButtonGroup | CraftEntryTypeBlockRichTextMarginals | CraftEntryTypeBlockProjectTeaser)[] | null
    entrySettings: CraftContentBlockEntrySettings | null
}

export interface CraftEntryTypeEntryLandingpage {
    title: string
    singleSeoTitle: string | null
    textHero: CraftContentBlockTextHero | null
    imageCover: CraftEntryTypeBlockImageCover | null
    singleRelatedProjects: (CraftEntryRelation)[] | null
    contentBuilder: (CraftEntryTypeBlockButton | CraftEntryTypeBlockCode | CraftEntryTypeBlockEmbed | CraftEntryTypeBlockFaq | CraftEntryTypeBlockHeadline | CraftEntryTypeBlockImageCover | CraftEntryTypeBlockImageGrid | CraftEntryTypeBlockImageSlider | CraftEntryTypeBlockIndividualEntryGrid | CraftEntryTypeBlockJobs | CraftEntryTypeBlockQuote | CraftEntryTypeBlockRelatedProjects | CraftEntryTypeBlockRichText | CraftEntryTypeBlockSalaryBand | CraftEntryTypeBlockImageCoverDeprecated | CraftEntryTypeBlockButtonGroup | CraftEntryTypeBlockRichTextMarginals | CraftEntryTypeBlockProjectTeaser)[] | null
    entrySettings: CraftContentBlockEntrySettings | null
}

export interface CraftEntryTypeEntryModules {
    title: string
    contentBuilder: (CraftEntryTypeBlockButton | CraftEntryTypeBlockCode | CraftEntryTypeBlockEmbed | CraftEntryTypeBlockFaq | CraftEntryTypeBlockHeadline | CraftEntryTypeBlockImageCover | CraftEntryTypeBlockImageGrid | CraftEntryTypeBlockImageSlider | CraftEntryTypeBlockIndividualEntryGrid | CraftEntryTypeBlockJobs | CraftEntryTypeBlockQuote | CraftEntryTypeBlockRelatedProjects | CraftEntryTypeBlockRichText | CraftEntryTypeBlockSalaryBand | CraftEntryTypeBlockImageCoverDeprecated | CraftEntryTypeBlockButtonGroup | CraftEntryTypeBlockRichTextMarginals | CraftEntryTypeBlockProjectTeaser)[] | null
}

export interface CraftEntryTypeEntryNewsletter {
    title: string
    singleIntroText: string | null
}

export interface CraftEntryTypeEntryNewsletterTransaction {
    title: string
    singleSeoTitle: string | null
    singleIntroText: string | null
}

export interface CraftEntryTypeEntryNoContent {
    title: string
}

export interface CraftEntryTypeEntryPages {
    title: string
    textHero: CraftContentBlockTextHero | null
    contentBuilder: (CraftEntryTypeBlockButton | CraftEntryTypeBlockCode | CraftEntryTypeBlockEmbed | CraftEntryTypeBlockFaq | CraftEntryTypeBlockHeadline | CraftEntryTypeBlockImageCover | CraftEntryTypeBlockImageGrid | CraftEntryTypeBlockImageSlider | CraftEntryTypeBlockIndividualEntryGrid | CraftEntryTypeBlockJobs | CraftEntryTypeBlockQuote | CraftEntryTypeBlockRelatedProjects | CraftEntryTypeBlockRichText | CraftEntryTypeBlockSalaryBand | CraftEntryTypeBlockImageCoverDeprecated | CraftEntryTypeBlockButtonGroup | CraftEntryTypeBlockRichTextMarginals | CraftEntryTypeBlockProjectTeaser)[] | null
    entrySettings: CraftContentBlockEntrySettings | null
}

export interface CraftEntryTypeEntryPartner {
    title: string
    singleLink: CraftLinkIt | null
}

export interface CraftEntryTypeEntryPromotionType {
    title: string
}

export interface CraftEntryTypeEntryReference {
    title: string
    singleSeoTitle: string | null
    singleIntroText: string | null
    groupedProjectImages: CraftEntryTypeGroupedProjectImagesBlock
    singleImageEntry: CraftAsset | null
    newsletterImage: CraftAsset | null
    singleProjectTitle: string | null
    groupedProjectTeaserSlider: (CraftAsset)[] | null
    contentBuilderWork: (CraftEntryTypeBlockEmbed | CraftEntryTypeBlockHeadline | CraftEntryTypeBlockButton | CraftEntryTypeBlockImageCover | CraftEntryTypeBlockImageDouble | CraftEntryTypeBlockImageGrid | CraftEntryTypeBlockImageSlider | CraftEntryTypeBlockRichText | CraftEntryTypeBlockQuote | CraftEntryTypeBlockImageGridCalculated | CraftEntryTypeBlockImageCoverDeprecated)[] | null
    settingsAppHeader: boolean | null
    singleAuthor: (CraftEntryRelation)[]
    categoryClient: (CraftEntryRelation)[] | null
    categoryPartner: (CraftEntryRelation)[] | null
    singleRelatedProjects: (CraftEntryRelation)[] | null
    categoryUnit: (CraftEntryRelation)[] | null
    categoryAwards: (CraftEntryRelation)[] | null
    categoryService: (CraftEntryRelation)[]
    entrySettings: CraftContentBlockEntrySettings | null
    unitIds: string
}

export interface CraftEntryTypeEntryService {
    title: string
    entrySettings: CraftContentBlockEntrySettings | null
}

export interface CraftEntryTypeEntryServices {
    title: string
    textHero: CraftContentBlockTextHero | null
    contentBuilder: (CraftEntryTypeBlockButton | CraftEntryTypeBlockCode | CraftEntryTypeBlockEmbed | CraftEntryTypeBlockFaq | CraftEntryTypeBlockHeadline | CraftEntryTypeBlockImageCover | CraftEntryTypeBlockImageGrid | CraftEntryTypeBlockImageSlider | CraftEntryTypeBlockIndividualEntryGrid | CraftEntryTypeBlockJobs | CraftEntryTypeBlockQuote | CraftEntryTypeBlockRelatedProjects | CraftEntryTypeBlockRichText | CraftEntryTypeBlockSalaryBand | CraftEntryTypeBlockImageCoverDeprecated | CraftEntryTypeBlockButtonGroup | CraftEntryTypeBlockRichTextMarginals | CraftEntryTypeBlockProjectTeaser)[] | null
}

export interface CraftEntryTypeEntrySize {
    title: string
}

export interface CraftEntryTypeEntryTeam {
    title: string
    singleSeoTitle: string | null
    singleRichText: string
    singleImageEntry: CraftAsset
    entrySettings: CraftContentBlockEntrySettings | null
}

export interface CraftEntryTypeEntryTextOnly {
    title: string
    singleIntroText: string | null
}

export interface CraftEntryTypeEntryUnit {
    title: string
    categoryService: (CraftEntryRelation)[] | null
    singleSeoTitle: string | null
    groupedProjectGrid: (CraftEntryTypeGroupedSingle | CraftEntryTypeGroupedDoubles | CraftEntryTypeGroupedQuadruplets)[] | null
}

export interface CraftEntryTypeEntryWork {
    title: string
    textHero: CraftContentBlockTextHero | null
    contentBuilder: (CraftEntryTypeBlockButton | CraftEntryTypeBlockCode | CraftEntryTypeBlockEmbed | CraftEntryTypeBlockFaq | CraftEntryTypeBlockHeadline | CraftEntryTypeBlockImageCover | CraftEntryTypeBlockImageGrid | CraftEntryTypeBlockImageSlider | CraftEntryTypeBlockIndividualEntryGrid | CraftEntryTypeBlockJobs | CraftEntryTypeBlockQuote | CraftEntryTypeBlockRelatedProjects | CraftEntryTypeBlockRichText | CraftEntryTypeBlockSalaryBand | CraftEntryTypeBlockImageCoverDeprecated | CraftEntryTypeBlockButtonGroup | CraftEntryTypeBlockRichTextMarginals | CraftEntryTypeBlockProjectTeaser)[] | null
    relatedFaqs: (CraftEntryRelation)[] | null
    entrySettings: CraftContentBlockEntrySettings | null
}

export interface CraftEntryTypeEntryWorkTag {
    title: string
}

export interface CraftEntryTypeGroupedDoubles {
    entries: (CraftEntryRelation)[] | null
    style: CraftOptionStyle | null
}

export interface CraftEntryTypeGroupedProjectImagesBlock {
    stage: CraftAsset
    gridLandscape: CraftAsset | null
    gridPortrait: CraftAsset
    vimeoVideoId: string | null
}

export interface CraftEntryTypeGroupedProjectInfoBlock {
    projectTitle: string | null
    briefing: string | null
    solution: string | null
}

export interface CraftEntryTypeGroupedQuadruplets {
    entries: (CraftEntryRelation)[] | null
}

export interface CraftEntryTypeGroupedSingle {
    entries: CraftEntryRelation | null
}

export interface CraftEntryTypeImagesBlock {
    image: CraftAsset
    linkInfo: CraftLinkIt | null
    linkInfo2: CraftLinkIt | null
}

export interface CraftEntryTypeLocations {
    title: string
    location: string | null
    address: string | null
    telephone: string | null
    locationImages: (CraftAsset)[] | null
    page: CraftLinkIt | null
}

export interface CraftEntryTypeSettingsButtonGroupBlock {
    style: CraftOptionStyle | null
    alignment: CraftOptionAlignment | null
}

export interface CraftEntryTypeSettingsEmbedBlock {
    embedPosition: CraftOptionEmbedPosition
    embedWidth: CraftOptionEmbedWidth
}

export interface CraftEntryTypeSettingsHeadlineBlock {
    size: CraftOptionSize
}

export interface CraftEntryTypeSettingsImageCoverBlock {
    backgroundPosition: CraftOptionBackgroundPosition | null
    textVerticalPosition: CraftOptionTextVerticalPosition | null
    textAlignment: CraftOptionTextAlignment | null
}

export interface CraftEntryTypeSettingsImageDoubleBlock {
    columnRatio: CraftOptionColumnRatio | null
}

export interface CraftEntryTypeSettingsImageGridBlock {
    showCaption: boolean | null
    layoutImageGrid: boolean | null
    columns: CraftOptionColumns
    splitOrientation: boolean | null
    imageRatio: CraftOptionImageRatio
}

export interface CraftEntryTypeSettingsImageSliderBlock {
    showCaption: boolean | null
    imageRatio: CraftOptionImageRatio
}

export interface CraftEntryTypeSingleButtonGroupBlock {
    button: CraftLinkIt | null
}

export interface CraftPageEntryArticleTag extends CraftEntryTypeEntryArticleTag {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryArticleType extends CraftEntryTypeEntryArticleType {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryArticle extends CraftEntryTypeEntryArticle {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryAwardType extends CraftEntryTypeEntryAwardType {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryClient extends CraftEntryTypeEntryClient {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryTextOnly extends CraftEntryTypeEntryTextOnly {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryGridImageWithText extends CraftEntryTypeEntryGridImageWithText {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryEmbed extends CraftEntryTypeEntryEmbed {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryNoContent extends CraftEntryTypeEntryNoContent {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryGridImage extends CraftEntryTypeEntryGridImage {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageBlockAccordionContent extends CraftEntryTypeBlockAccordionContent {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryGender extends CraftEntryTypeEntryGender {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryGlobals extends CraftEntryTypeEntryGlobals {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryHomepage extends CraftEntryTypeEntryHomepage {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryJob extends CraftEntryTypeEntryJob {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryModules extends CraftEntryTypeEntryModules {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryAbout extends CraftEntryTypeEntryAbout {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryArticles extends CraftEntryTypeEntryArticles {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryJobs extends CraftEntryTypeEntryJobs {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryLandingpage extends CraftEntryTypeEntryLandingpage {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryPages extends CraftEntryTypeEntryPages {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryServices extends CraftEntryTypeEntryServices {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryWork extends CraftEntryTypeEntryWork {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryNewsletter extends CraftEntryTypeEntryNewsletter {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryNewsletterTransaction extends CraftEntryTypeEntryNewsletterTransaction {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryPartner extends CraftEntryTypeEntryPartner {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryPromotionType extends CraftEntryTypeEntryPromotionType {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryService extends CraftEntryTypeEntryService {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntrySize extends CraftEntryTypeEntrySize {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryTeam extends CraftEntryTypeEntryTeam {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryUnit extends CraftEntryTypeEntryUnit {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryCaseStudy extends CraftEntryTypeEntryCaseStudy {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryReference extends CraftEntryTypeEntryReference {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}

export interface CraftPageEntryWorkTag extends CraftEntryTypeEntryWorkTag {
    metadata: CraftEntryMeta
    title: string
    sectionHandle: string
}



// --- users ---
export type CraftUser = {
    metadata: CraftUserMeta
    username: string | null
    fullName: string | null
    photo: CraftAsset | null
    email: string | null
}

// --- categories ---


// --- tables ---
export interface CraftTableSalaryRanges {
    col1: string
    learning: string
    col2: string
    proficient: string
    col3: string
    mastering: string
}

export interface CraftTableShopFacts {
    col1: string
    productFact: string
}



// --- options ---
export type CraftOptionValueExperienceLevel = 'learning' | 'proficient' | 'mastering'

export type CraftOptionExperienceLevel = {
    label: string
    selected: boolean
    valid: boolean
    icon: string | null
    color: string | null
    value: CraftOptionValueExperienceLevel
}

export type CraftOptionValueStyle = 'landscape' | 'portrait'

export type CraftOptionStyle = {
    label: string
    selected: boolean
    valid: boolean
    icon: string | null
    color: string | null
    value: CraftOptionValueStyle
}

export type CraftOptionValueImageRatio = '3:4' | '16:9'

export type CraftOptionImageRatio = {
    label: string
    selected: boolean
    valid: boolean
    icon: string | null
    color: string | null
    value: CraftOptionValueImageRatio
}

export type CraftOptionValueAlignment = 'left' | 'center' | 'right' | 'full'

export type CraftOptionAlignment = {
    label: string
    selected: boolean
    valid: boolean
    icon: string | null
    color: string | null
    value: CraftOptionValueAlignment
}

export type CraftOptionValueStyle3 = 'primary' | 'secondary'

export type CraftOptionStyle3 = {
    label: string
    selected: boolean
    valid: boolean
    icon: string | null
    color: string | null
    value: CraftOptionValueStyle3
}

export type CraftOptionValueEmbedPosition = 'left' | 'center' | 'right'

export type CraftOptionEmbedPosition = {
    label: string
    selected: boolean
    valid: boolean
    icon: string | null
    color: string | null
    value: CraftOptionValueEmbedPosition
}

export type CraftOptionValueEmbedWidth = 'full' | 'threeQuarter' | 'half'

export type CraftOptionEmbedWidth = {
    label: string
    selected: boolean
    valid: boolean
    icon: string | null
    color: string | null
    value: CraftOptionValueEmbedWidth
}

export type CraftOptionValueSize = 'h2' | 'h3' | 'h4' | 'h5' | 'h6'

export type CraftOptionSize = {
    label: string
    selected: boolean
    valid: boolean
    icon: string | null
    color: string | null
    value: CraftOptionValueSize
}

export type CraftOptionValueColumnRatio = 'smallLarge' | 'largeSmall'

export type CraftOptionColumnRatio = {
    label: string
    selected: boolean
    valid: boolean
    icon: string | null
    color: string | null
    value: CraftOptionValueColumnRatio
}

export type CraftOptionValueBackgroundPosition = 'focalpoint' | '0% 0%' | '0% 50%' | '0% 100%' | '50% 0%' | '50% 50%' | '50% 100%' | '100% 0%' | '100% 50%' | '100% 100%'

export type CraftOptionBackgroundPosition = {
    label: string
    selected: boolean
    valid: boolean
    icon: string | null
    color: string | null
    value: CraftOptionValueBackgroundPosition
}

export type CraftOptionValueTextAlignment = 'left' | 'center' | 'right'

export type CraftOptionTextAlignment = {
    label: string
    selected: boolean
    valid: boolean
    icon: string | null
    color: string | null
    value: CraftOptionValueTextAlignment
}

export type CraftOptionValueTextVerticalPosition = 'top' | 'center' | 'bottom'

export type CraftOptionTextVerticalPosition = {
    label: string
    selected: boolean
    valid: boolean
    icon: string | null
    color: string | null
    value: CraftOptionValueTextVerticalPosition
}

export type CraftOptionValueColumns = '3' | '2' | '1'

export type CraftOptionColumns = {
    label: string
    selected: boolean
    valid: boolean
    icon: string | null
    color: string | null
    value: CraftOptionValueColumns
}

export type CraftOptionValueSingleCodeLanguage = 'html' | 'scss' | 'twig' | 'javascript' | 'vue' | 'php' | 'markdown' | 'json' | 'bash'

export type CraftOptionSingleCodeLanguage = {
    label: string
    selected: boolean
    valid: boolean
    icon: string | null
    color: string | null
    value: CraftOptionValueSingleCodeLanguage
}

export type CraftOptionValueSingleJobLocation = 'linz' | 'linzWien' | 'linzWienRemote' | 'neufelden' | 'gleisdorf'

export type CraftOptionSingleJobLocation = {
    label: string
    selected: boolean
    valid: boolean
    icon: string | null
    color: string | null
    value: CraftOptionValueSingleJobLocation
}



// --- contentBlocks ---
export interface CraftContentBlockEntrySettings {
    footerTopText: string | null
}

export interface CraftContentBlockFaqs {
    singleHeadline: string | null
    relatedFaqs: (CraftEntryRelation)[] | null
}

export interface CraftContentBlockTextHero {
    headline: string | null
    richTextSimple: string | null
}

export interface CraftContentBlockTextWithStickers {
    desktopText: string
}



// --- customHardTypes ---
export type CraftLinkItTypes = 'Entry' | 'Asset' | 'Email Address' | 'Phone' | 'Url'

export type CraftLinkIt = {
    metadata : {
        type: CraftLinkItTypes
    }
    label: string
    url: string
    path: string
    target: CraftLinkTarget
}

